/control/verbose 1
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

/run/initialize

/vis/open VRML2FILE
/vis/viewer/set/autoRefresh false
/vis/viewer/set/viewpointThetaPhi 60 35 deg
/vis/viewer/zoom 1.4
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 1

/tracking/storeTrajectory 1

/gun/particle mu-
/gun/energy 8 GeV
/gun/position 0.1 0.1 -250 mm
/gun/direction 0 0 1

/run/printProgress 1
/run/beamOn 1

/vis/viewer/flush
